# Light Escape Environment
# Advanced task requiring movement away from light source.

task: LIGHT_ESCAPE
simulation_time: 100000.0
num_physics_steps_per_control_step: 10
time_scale: 2
camera_ids: [0, 1]
render_size: [480, 640]
joint_randomization_noise_scale: 0.0
target_distance: 3.0
light_perlin_noise_scale: 200 # Must be integer factor of 200
