# Configuration for debug session
exp_name: "debug-experiment"
seed: 42
track: true
wandb_project_name: "Let's-find-that-bug"
wandb_entity: "SEL3-2026-Groep-4"
 
num_envs: 32
num_steps: 32
total_timesteps: 102400
num_arms: 2
num_segments_per_arm: 1
cuda: true

