architecture:
  critic:
    activation: tanh
    hidden_dims: []
  feature_extractor:
    activation: tanh
    hidden_dims:
    - 300
    - 300
    - 300
  message_passing_steps: null
  motor:
    activation: tanh
    hidden_dims: []
  name: centralized
  propagator: null
  sensor:
    activation: tanh
    hidden_dims:
    - 300
    - 300
    - 300
  topology_type: null
arena:
  attach_target: true
  sand_ground_color: true
  size:
  - 10.0
  - 5.0
  wall_height: 1.5
  wall_thickness: 0.1
environment:
  camera_ids:
  - 0
  - 1
  joint_randomization_noise_scale: 0.0
  light_perlin_noise_scale: 0
  num_physics_steps_per_control_step: 10
  render_size:
  - 480
  - 640
  simulation_time: 5000.0
  target_distance: 3.0
  task: !!python/object/apply:brittle_star_project.environment.env_types.Task
  - directed_locomotion
  time_scale: 2
experiment:
  base_run_dir: runs
  cuda: true
  debug_sanity: false
  exp_name: lr lowered
  seed: 42
  torch_deterministic: true
logging:
  capture_video: false
  checkpoint_frequency: 100
  hf_entity: ''
  save_checkpoints: true
  save_model: true
  track: true
  upload_checkpoints: false
  upload_final_model: true
  wandb_entity: SEL3-2026-Groep-4
  wandb_project_name: Reducing randomness
morphology:
  segments_per_arm:
  - 4
  - 0
  - 4
  - 0
  - 0
  use_p_control: true
  use_torque_control: false
ppo:
  anneal_lr: true
  clip_coef: 0.2
  clip_vloss: true
  ent_coef: 0.001
  gae_lambda: 0.95
  gamma: 0.99
  learning_rate: 0.0001
  max_grad_norm: 0.5
  norm_adv: true
  num_envs: 32
  num_minibatches: 32
  num_steps: 64
  target_kl: 0.02
  total_timesteps: 1228800
  update_epochs: 4
  vf_coef: 1.0
simulation:
  backend: !!python/object/apply:brittle_star_project.environment.env_types.Backend
  - MJX
  model_path: null
  model_type: random